/** Static status code response descriptions from BulkSMSBD API. */
export const BULK_SMS_RESPONSES: Record<number, string> = {
  202: "SMS Submitted Successfully",
  1001: "Invalid Number",
  1002: "Sender ID not correct / Sender ID is disabled",
  1003: "Please Required all fields / Contact Your System Administrator",
  1005: "Internal Error",
  1006: "Balance Validity Not Available",
  1007: "Balance Insufficient",
  1011: "User ID not found",
  1012: "Masking SMS must be sent in Bengali",
  1013: "Sender ID has not found Gateway by API Key",
  1014: "Sender Type Name not found using this sender by API Key",
  1015: "Sender ID has not found Any Valid Gateway by API Key",
  1016: "Sender Type Name Active Price Info not found by this sender ID",
  1017: "Sender Type Name Price Info not found by this sender ID",
  1018: "The Owner of this (username) Account is disabled",
  1019: "The (sender type name) Price of this (username) Account is disabled",
  1020: "The parent of this account is not found.",
  1021: "The parent active (sender type name) price of this account is not found.",
  1031: "Your Account Not Verified, Please Contact Administrator.",
  1032: "IP Not whitelisted",
};
